//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WurmRancher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WurmRancher.WRResources", typeof(WRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.IO.UnmanagedMemoryStream apple_crunch {
            get {
                return ResourceManager.GetStream("apple_crunch", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream big_monster {
            get {
                return ResourceManager.GetStream("big_monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wurm Rancher, v1.0
        ///concept and programming by Drew Johnson
        ///created using Microsoft Silverlight 5
        ///
        ///I would love to hear any comments or suggestions!  Please email me at werd2.718@gmail.com.
        ///
        ///I did the artwork for the creatures and plants, but I don’t have the patience or skill to make them look good.  If you would like to collaborate by doing some artwork, please email me!
        ///
        ///Thanks to Marcel Vijfwinkel of cgtextures.com for making available the awesome pictures used in the background.
        ///
        ///Thanks to Dec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream dragon {
            get {
                return ResourceManager.GetStream("dragon", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream electic_buzz {
            get {
                return ResourceManager.GetStream("electic_buzz", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream feeder {
            get {
                return ResourceManager.GetStream("feeder", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream good_grass_new {
            get {
                return ResourceManager.GetStream("good_grass_new", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream good_grass_new_sprayed {
            get {
                return ResourceManager.GetStream("good_grass_new_sprayed", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream grass_eater {
            get {
                return ResourceManager.GetStream("grass_eater", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream gruntz {
            get {
                return ResourceManager.GetStream("gruntz", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream insect10 {
            get {
                return ResourceManager.GetStream("insect10", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream insect11 {
            get {
                return ResourceManager.GetStream("insect11", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream insect9 {
            get {
                return ResourceManager.GetStream("insect9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial:
        ///If you want to get started right away, try the tutorial. Under the main menu, click New Game and in the Select a Mission menu, select Tutorial. If you want to get the details, read on.
        ///
        ///Backstory:
        ///A new opportunity has opened up for brave and enterprising farmers on the recently discovered planet of Krytoc III. A species of giant snake-like creatures, called “wurms”, can fetch a wonderful price. Wild ones are impossible to tame, but if they are raised in captivity they can be quite useful. You [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream IntroScreen {
            get {
                return ResourceManager.GetStream("IntroScreen", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream laser2 {
            get {
                return ResourceManager.GetStream("laser2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream monster {
            get {
                return ResourceManager.GetStream("monster", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream monster_eye {
            get {
                return ResourceManager.GetStream("monster_eye", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream monster_eye_shot {
            get {
                return ResourceManager.GetStream("monster_eye_shot", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream pain_b {
            get {
                return ResourceManager.GetStream("pain_b", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream pains {
            get {
                return ResourceManager.GetStream("pains", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream parasite {
            get {
                return ResourceManager.GetStream("parasite", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream pig_grunt {
            get {
                return ResourceManager.GetStream("pig_grunt", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream poison_weed {
            get {
                return ResourceManager.GetStream("poison_weed", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream poison_weed_sprayed {
            get {
                return ResourceManager.GetStream("poison_weed_sprayed", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream rancher {
            get {
                return ResourceManager.GetStream("rancher", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream SandPebblesBrown {
            get {
                return ResourceManager.GetStream("SandPebblesBrown", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream SandPebblesRed {
            get {
                return ResourceManager.GetStream("SandPebblesRed", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream seeded {
            get {
                return ResourceManager.GetStream("seeded", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream seeds {
            get {
                return ResourceManager.GetStream("seeds", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream Snow {
            get {
                return ResourceManager.GetStream("Snow", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream SoilBeach {
            get {
                return ResourceManager.GetStream("SoilBeach", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream SoilCracked {
            get {
                return ResourceManager.GetStream("SoilCracked", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream SoilMud {
            get {
                return ResourceManager.GetStream("SoilMud", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream spray_can {
            get {
                return ResourceManager.GetStream("spray_can", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream squish {
            get {
                return ResourceManager.GetStream("squish", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream weed {
            get {
                return ResourceManager.GetStream("weed", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream weedsprayed {
            get {
                return ResourceManager.GetStream("weedsprayed", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream wurm_body {
            get {
                return ResourceManager.GetStream("wurm_body", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream wurm_head {
            get {
                return ResourceManager.GetStream("wurm_head", resourceCulture);
            }
        }
    }
}
